*** empty log message ***

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2073,18 +2073,15 @@ if test "${japanese}" = "no"; then
     OPT_LANGUAGE=en
     TK_LANGUAGE=ENGLISH
     
-    
     OPT_WAKATI_DEFAULT="none"
 else
     OPT_LANGUAGE=ja
-    TK_LANGUAGE=JAPANESE
     # Check whether --with-lang or --without-lang was given.
 if test "${with_lang+set}" = set; then
   withval="$with_lang"
   OPT_LANGUAGE=$with_lang
 fi
 
-    
     
 
     # Check whether --with-nkf or --without-nkf was given.
@@ -2095,7 +2092,7 @@ if test "${with_nkf+set}" = set; then
 else
   if test -z "$NKF"; then
 		echo $ac_n "checking for NKF module""... $ac_c" 1>&6
-echo "configure:2099: checking for NKF module" >&5
+echo "configure:2096: checking for NKF module" >&5
 		if $PERL -MNKF -e '' 1>/dev/null 2> /dev/null; then
 		    NKF=module_nkf
 		    echo "$ac_t""yes" 1>&6
@@ -2104,7 +2101,7 @@ echo "configure:2099: checking for NKF module" >&5
 		    # Extract the first word of "nkf", so it can be a program name with args.
 set dummy nkf; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2108: checking for $ac_word" >&5
+echo "configure:2105: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_NKF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2154,7 +2151,7 @@ if test "${with_kakasi+set}" = set; then
 else
   if test -z "$KAKASI"; then
 		echo $ac_n "checking for Text::Kakasi module""... $ac_c" 1>&6
-echo "configure:2158: checking for Text::Kakasi module" >&5
+echo "configure:2155: checking for Text::Kakasi module" >&5
 		if $PERL -MText::Kakasi -e '' 1>/dev/null 2> /dev/null; then
 		    KAKASI=module_kakasi
 		    echo "$ac_t""yes" 1>&6
@@ -2163,7 +2160,7 @@ echo "configure:2158: checking for Text::Kakasi module" >&5
 		    # Extract the first word of "kakasi", so it can be a program name with args.
 set dummy kakasi; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2167: checking for $ac_word" >&5
+echo "configure:2164: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_KAKASI'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2209,7 +2206,7 @@ if test "${with_chasen+set}" = set; then
 else
   if test -z "$CHASEN"; then
 		echo $ac_n "checking for Text::ChaSen1 module""... $ac_c" 1>&6
-echo "configure:2213: checking for Text::ChaSen1 module" >&5
+echo "configure:2210: checking for Text::ChaSen1 module" >&5
 		if $PERL -MText::ChaSen1 -e '' 1>/dev/null 2> /dev/null; then
 		    CHASEN=module_chasen1
 		    echo "$ac_t""yes" 1>&6
@@ -2218,7 +2215,7 @@ echo "configure:2213: checking for Text::ChaSen1 module" >&5
 		    # Extract the first word of "chasen", so it can be a program name with args.
 set dummy chasen; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2222: checking for $ac_word" >&5
+echo "configure:2219: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_CHASEN'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2261,7 +2258,7 @@ fi
     fi
 
     echo $ac_n "checking for default wakatigaki processor""... $ac_c" 1>&6
-echo "configure:2265: checking for default wakatigaki processor" >&5
+echo "configure:2262: checking for default wakatigaki processor" >&5
     OPT_WAKATI_DEFAULT=
     if test "$KAKASI" != "no"; then
 	OPT_WAKATI_DEFAULT=KAKASI
@@ -2298,7 +2295,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2302: checking for $ac_word" >&5
+echo "configure:2299: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_WISH'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2350,7 +2347,7 @@ else
   # Extract the first word of "lynx", so it can be a program name with args.
 set dummy lynx; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2354: checking for $ac_word" >&5
+echo "configure:2351: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_LYNX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2391,23 +2388,18 @@ fi
             TKNAMAZU=""
         else
             TKNAMAZU="tknamazu"
-        fi
-    fi
-fi
-
-
-# Check whether --with-groff or --without-groff was given.
+            # Check whether --with-groff or --without-groff was given.
 if test "${with_groff+set}" = set; then
   withval="$with_groff"
   echo "$ac_t""using $with_groff for groff" 1>&6
-	GROFF = $with_groff
+				GROFF = $with_groff
 else
   for ac_prog in jgroff groff nroff
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2411: checking for $ac_word" >&5
+echo "configure:2403: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GROFF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2443,22 +2435,22 @@ test -n "$GROFF" && break
 done
 test -n "$GROFF" || GROFF="no"
 
-
+            
 fi
 
-if test "$GROFF" = "no"; then
-    echo "configure: warning: *** groff not found: tknamazu cannot browse man pages ***" 1>&2
-fi
-# Check whether --with-info or --without-info was given.
+            if test "$GROFF" = "no"; then
+                echo "configure: warning: *** groff not found: tknamazu cannot browse man pages ***" 1>&2
+            fi
+            # Check whether --with-info or --without-info was given.
 if test "${with_info+set}" = set; then
   withval="$with_info"
   echo "$ac_t""using $with_info for info" 1>&6
-	INFO = $with_info
+				INFO = $with_info
 else
   # Extract the first word of "info", so it can be a program name with args.
 set dummy info; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2462: checking for $ac_word" >&5
+echo "configure:2454: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_INFO'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2491,22 +2483,22 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-
+            
 fi
 
-if test "$INFO" = "no"; then
-    echo "configure: warning: *** info not found: tknamazu cannot browse info files ***" 1>&2
-fi
-# Check whether --with-zcat or --without-zcat was given.
+            if test "$INFO" = "no"; then
+                echo "configure: warning: *** info not found: tknamazu cannot browse info files ***" 1>&2
+            fi
+            # Check whether --with-zcat or --without-zcat was given.
 if test "${with_zcat+set}" = set; then
   withval="$with_zcat"
   echo "$ac_t""using $with_zcat for zcat" 1>&6
-	ZCAT = $with_zcat
+				ZCAT = $with_zcat
 else
   # Extract the first word of "zcat", so it can be a program name with args.
 set dummy zcat; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2510: checking for $ac_word" >&5
+echo "configure:2502: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_ZCAT'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2539,11 +2531,16 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
-
+            
 fi
 
-if test "$ZCAT" = "no"; then
-    echo "configure: warning: zcat not found" 1>&2
+            if test "$ZCAT" = "no"; then
+                echo "configure: warning: zcat not found" 1>&2
+            fi
+            subdirs="tknamazu"
+
+        fi
+    fi
 fi
 
 
@@ -2553,7 +2550,7 @@ fi
 tmp=`$PERL -nle 'print \$1 if /^\\$VERSION = "([\d\.]+)";\$/' \
 	File-MMagic/MMagic.pm`
 echo $ac_n "checking for File::MMagic module""... $ac_c" 1>&6
-echo "configure:2557: checking for File::MMagic module" >&5
+echo "configure:2554: checking for File::MMagic module" >&5
 if $PERL -e "use File::MMagic $tmp" 1>/dev/null 2> /dev/null; then
     echo "$ac_t""yes" 1>&6
     FILE_MMAGIC=""
@@ -2611,7 +2608,7 @@ fi
 
 webmaster="webmaster@${hostname}${domainname}"
 echo $ac_n "checking for admin's email address""... $ac_c" 1>&6
-echo "configure:2615: checking for admin's email address" >&5
+echo "configure:2612: checking for admin's email address" >&5
 # Check whether --with-admin or --without-admin was given.
 if test "${with_admin+set}" = set; then
   withval="$with_admin"
@@ -2625,6 +2622,7 @@ echo "$ac_t""$admin" 1>&6
 OPT_ADMIN_EMAIL=$admin
 
 
+
 if test -n "$EMXOS2"; then
     CFLAGS="-O2 -m486 -Zmtd"
     LDFLAGS="-m486 -Zmtd -Zcrtdll -Zsysv-signals -Zbin-files"
@@ -2632,7 +2630,7 @@ fi
 
 
 echo $ac_n "checking for a scoring method""... $ac_c" 1>&6
-echo "configure:2636: checking for a scoring method" >&5
+echo "configure:2634: checking for a scoring method" >&5
 # Check whether --with-scoring or --without-scoring was given.
 if test "${with_scoring+set}" = set; then
   withval="$with_scoring"
@@ -2794,7 +2792,7 @@ ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
 
 trap 'rm -fr `echo "Makefile src/Makefile conf/Makefile lib/var.pl lib/conf.pl
-src/mknmz.pl src/gcnmz src/gtnmz src/mailutime namazu.spec tknamazu/Makefile tknamazu/tknamazu.tcl config.h" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+src/mknmz.pl src/gcnmz src/gtnmz src/mailutime namazu.spec config.h" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -2846,17 +2844,17 @@ s%@ALLOCA@%$ALLOCA%g
 s%@LIBOBJS@%$LIBOBJS%g
 s%@PERL@%$PERL%g
 s%@OPT_LANGUAGE@%$OPT_LANGUAGE%g
-s%@TK_LANGUAGE@%$TK_LANGUAGE%g
 s%@NKF@%$NKF%g
 s%@KAKASI@%$KAKASI%g
 s%@CHASEN@%$CHASEN%g
 s%@OPT_WAKATI_DEFAULT@%$OPT_WAKATI_DEFAULT%g
 s%@WISH@%$WISH%g
 s%@LYNX@%$LYNX%g
-s%@TKNAMAZU@%$TKNAMAZU%g
 s%@GROFF@%$GROFF%g
 s%@INFO@%$INFO%g
 s%@ZCAT@%$ZCAT%g
+s%@subdirs@%$subdirs%g
+s%@TKNAMAZU@%$TKNAMAZU%g
 s%@FILE_MMAGIC@%$FILE_MMAGIC%g
 s%@OPT_ADMIN_EMAIL@%$OPT_ADMIN_EMAIL%g
 s%@OPT_SCORING@%$OPT_SCORING%g
@@ -2903,7 +2901,7 @@ EOF
 cat >> $CONFIG_STATUS <<EOF
 
 CONFIG_FILES=\${CONFIG_FILES-"Makefile src/Makefile conf/Makefile lib/var.pl lib/conf.pl
-src/mknmz.pl src/gcnmz src/gtnmz src/mailutime namazu.spec tknamazu/Makefile tknamazu/tknamazu.tcl"}
+src/mknmz.pl src/gcnmz src/gtnmz src/mailutime namazu.spec"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
@@ -3082,6 +3080,103 @@ EOF
 chmod +x $CONFIG_STATUS
 rm -fr confdefs* $ac_clean_files
 test "$no_create" = yes || ${CONFIG_SHELL-/bin/sh} $CONFIG_STATUS || exit 1
+
+if test "$no_recursion" != yes; then
+
+  # Remove --cache-file and --srcdir arguments so they do not pile up.
+  ac_sub_configure_args=
+  ac_prev=
+  for ac_arg in $ac_configure_args; do
+    if test -n "$ac_prev"; then
+      ac_prev=
+      continue
+    fi
+    case "$ac_arg" in
+    -cache-file | --cache-file | --cache-fil | --cache-fi \
+    | --cache-f | --cache- | --cache | --cach | --cac | --ca | --c)
+      ac_prev=cache_file ;;
+    -cache-file=* | --cache-file=* | --cache-fil=* | --cache-fi=* \
+    | --cache-f=* | --cache-=* | --cache=* | --cach=* | --cac=* | --ca=* | --c=*)
+      ;;
+    -srcdir | --srcdir | --srcdi | --srcd | --src | --sr)
+      ac_prev=srcdir ;;
+    -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=*)
+      ;;
+    *) ac_sub_configure_args="$ac_sub_configure_args $ac_arg" ;;
+    esac
+  done
+
+  for ac_config_dir in tknamazu; do
+
+    # Do not complain, so a configure script can configure whichever
+    # parts of a large source tree are present.
+    if test ! -d $srcdir/$ac_config_dir; then
+      continue
+    fi
+
+    echo configuring in $ac_config_dir
+
+    case "$srcdir" in
+    .) ;;
+    *)
+      if test -d ./$ac_config_dir || mkdir ./$ac_config_dir; then :;
+      else
+        { echo "configure: error: can not create `pwd`/$ac_config_dir" 1>&2; exit 1; }
+      fi
+      ;;
+    esac
+
+    ac_popdir=`pwd`
+    cd $ac_config_dir
+
+      # A "../" for each directory in /$ac_config_dir.
+      ac_dots=`echo $ac_config_dir|sed -e 's%^\./%%' -e 's%[^/]$%&/%' -e 's%[^/]*/%../%g'`
+
+    case "$srcdir" in
+    .) # No --srcdir option.  We are building in place.
+      ac_sub_srcdir=$srcdir ;;
+    /*) # Absolute path.
+      ac_sub_srcdir=$srcdir/$ac_config_dir ;;
+    *) # Relative path.
+      ac_sub_srcdir=$ac_dots$srcdir/$ac_config_dir ;;
+    esac
+
+    # Check for guested configure; otherwise get Cygnus style configure.
+    if test -f $ac_sub_srcdir/configure; then
+      ac_sub_configure=$ac_sub_srcdir/configure
+    elif test -f $ac_sub_srcdir/configure.in; then
+      ac_sub_configure=$ac_configure
+    else
+      echo "configure: warning: no configuration information is in $ac_config_dir" 1>&2
+      ac_sub_configure=
+    fi
+
+    # The recursion is here.
+    if test -n "$ac_sub_configure"; then
+
+      # Make the cache file name correct relative to the subdirectory.
+      case "$cache_file" in
+      /*) ac_sub_cache_file=$cache_file ;;
+      *) # Relative path.
+        ac_sub_cache_file="$ac_dots$cache_file" ;;
+      esac
+  case "$ac_given_INSTALL" in
+        [/$]*) INSTALL="$ac_given_INSTALL" ;;
+        *) INSTALL="$ac_dots$ac_given_INSTALL" ;;
+        esac
+
+      echo "running ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir"
+      # The eval makes quoting arguments work.
+      if eval ${CONFIG_SHELL-/bin/sh} $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir
+      then :
+      else
+        { echo "configure: error: $ac_sub_configure failed for $ac_config_dir" 1>&2; exit 1; }
+      fi
+    fi
+
+    cd $ac_popdir
+  done
+fi
  
 
 # Local Variables:
