Remove wdnmz.in

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2452,12 +2452,222 @@ fi
 OPT_HELPER_ZCAT=$ZCAT
 
 
+# Extract the first word of "gzip", so it can be a program name with args.
+set dummy gzip; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2459: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_GZIP'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$GZIP" in
+  /*)
+  ac_cv_path_GZIP="$GZIP" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_GZIP="$GZIP" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_GZIP="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_GZIP" && ac_cv_path_GZIP="no"
+  ;;
+esac
+fi
+GZIP="$ac_cv_path_GZIP"
+if test -n "$GZIP"; then
+  echo "$ac_t""$GZIP" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$GZIP" = "no"; then
+    echo "configure: warning: gzip not found" 1>&2
+fi
+GZIP_PATH=$GZIP
+
+
+# Extract the first word of "bzip2", so it can be a program name with args.
+set dummy bzip2; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2501: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_BZIP2'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$BZIP2" in
+  /*)
+  ac_cv_path_BZIP2="$BZIP2" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_BZIP2="$BZIP2" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_BZIP2="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_BZIP2" && ac_cv_path_BZIP2="no"
+  ;;
+esac
+fi
+BZIP2="$ac_cv_path_BZIP2"
+if test -n "$BZIP2"; then
+  echo "$ac_t""$BZIP2" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$BZIP2" = "no"; then
+    echo "configure: warning: bzip2 not found" 1>&2
+fi
+BZIP2_PATH=$BZIP2
+
+
+# Extract the first word of "pdftotext", so it can be a program name with args.
+set dummy pdftotext; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2543: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_PDFTOTEXT'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$PDFTOTEXT" in
+  /*)
+  ac_cv_path_PDFTOTEXT="$PDFTOTEXT" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_PDFTOTEXT="$PDFTOTEXT" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_PDFTOTEXT="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_PDFTOTEXT" && ac_cv_path_PDFTOTEXT="no"
+  ;;
+esac
+fi
+PDFTOTEXT="$ac_cv_path_PDFTOTEXT"
+if test -n "$PDFTOTEXT"; then
+  echo "$ac_t""$PDFTOTEXT" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$PDFTOTEXT" = "no"; then
+    echo "configure: warning: pdftotext not found" 1>&2
+fi
+PDFTOTEXT_PATH=$PDFTOTEXT
+
+
+# Extract the first word of "mswordview", so it can be a program name with args.
+set dummy mswordview; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2585: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_MSWORDVIEW'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$MSWORDVIEW" in
+  /*)
+  ac_cv_path_MSWORDVIEW="$MSWORDVIEW" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_MSWORDVIEW="$MSWORDVIEW" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_MSWORDVIEW="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_MSWORDVIEW" && ac_cv_path_MSWORDVIEW="no"
+  ;;
+esac
+fi
+MSWORDVIEW="$ac_cv_path_MSWORDVIEW"
+if test -n "$MSWORDVIEW"; then
+  echo "$ac_t""$MSWORDVIEW" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$MSWORDVIEW" = "no"; then
+    echo "configure: warning: mswordview not found" 1>&2
+fi
+MSWORDVIEW_PATH=$MSWORDVIEW
+
+
+# Extract the first word of "lv", so it can be a program name with args.
+set dummy lv; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:2627: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_LV'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$LV" in
+  /*)
+  ac_cv_path_LV="$LV" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_LV="$LV" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_LV="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_LV" && ac_cv_path_LV="no"
+  ;;
+esac
+fi
+LV="$ac_cv_path_LV"
+if test -n "$LV"; then
+  echo "$ac_t""$LV" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+if test "$LV" = "no"; then
+    echo "configure: warning: lv not found" 1>&2
+fi
+LV_PATH=$LV
+
+
 for ac_prog in jgroff groff nroff
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:2461: checking for $ac_word" >&5
+echo "configure:2671: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GROFF'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -2512,7 +2722,7 @@ OPT_HELPER_MAN="$GROFF -man $GROFF_OPT"
 
 
 echo $ac_n "checking for OPT_CGI_LOCATION""... $ac_c" 1>&6
-echo "configure:2516: checking for OPT_CGI_LOCATION" >&5
+echo "configure:2726: checking for OPT_CGI_LOCATION" >&5
 # Check whether --with-cgi_location or --without-cgi_location was given.
 if test "${with_cgi_location+set}" = set; then
   withval="$with_cgi_location"
@@ -2568,7 +2778,7 @@ fi
 
 webmaster="webmaster@${hostname}${domainname}"
 echo $ac_n "checking for admin's email address""... $ac_c" 1>&6
-echo "configure:2572: checking for admin's email address" >&5
+echo "configure:2782: checking for admin's email address" >&5
 # Check whether --with-admin or --without-admin was given.
 if test "${with_admin+set}" = set; then
   withval="$with_admin"
@@ -2589,7 +2799,7 @@ fi
 
 
 echo $ac_n "checking for SCORING""... $ac_c" 1>&6
-echo "configure:2593: checking for SCORING" >&5
+echo "configure:2803: checking for SCORING" >&5
 # Check whether --with-scoring or --without-scoring was given.
 if test "${with_scoring+set}" = set; then
   withval="$with_scoring"
@@ -2734,6 +2944,8 @@ ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
 
 trap 'rm -fr `echo "Makefile src/Makefile lib/conf.pl src/mknmz.pl src/wdnmz
+filter/gzip.pl filter/compress.pl filter/man.pl filter/rfc.pl
+filter/bzip2.pl filter/msword.pl
 src/vfnmz src/gcnmz src/gtnmz src/mailutime src/clnmz src/rvnmz namazu.spec config.h" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
@@ -2794,6 +3006,16 @@ s%@CHASEN@%$CHASEN%g
 s%@OPT_WAKATI_DEFAULT@%$OPT_WAKATI_DEFAULT%g
 s%@ZCAT@%$ZCAT%g
 s%@OPT_HELPER_ZCAT@%$OPT_HELPER_ZCAT%g
+s%@GZIP@%$GZIP%g
+s%@GZIP_PATH@%$GZIP_PATH%g
+s%@BZIP2@%$BZIP2%g
+s%@BZIP2_PATH@%$BZIP2_PATH%g
+s%@PDFTOTEXT@%$PDFTOTEXT%g
+s%@PDFTOTEXT_PATH@%$PDFTOTEXT_PATH%g
+s%@MSWORDVIEW@%$MSWORDVIEW%g
+s%@MSWORDVIEW_PATH@%$MSWORDVIEW_PATH%g
+s%@LV@%$LV%g
+s%@LV_PATH@%$LV_PATH%g
 s%@GROFF@%$GROFF%g
 s%@OPT_HELPER_MAN@%$OPT_HELPER_MAN%g
 s%@OPT_CGI_LOCATION@%$OPT_CGI_LOCATION%g
@@ -2841,6 +3063,8 @@ EOF
 cat >> $CONFIG_STATUS <<EOF
 
 CONFIG_FILES=\${CONFIG_FILES-"Makefile src/Makefile lib/conf.pl src/mknmz.pl src/wdnmz
+filter/gzip.pl filter/compress.pl filter/man.pl filter/rfc.pl
+filter/bzip2.pl filter/msword.pl
 src/vfnmz src/gcnmz src/gtnmz src/mailutime src/clnmz src/rvnmz namazu.spec"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
